version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: sgx_minio
    ports:
      - "9000:9000" # Chỉ expose cổng API (9000), KHÔNG expose cổng Console (9001)
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    # Chạy MinIO server và không expose cổng Console (9001) ra ngoài để tiết kiệm tối đa tài nguyên
    command: server /data
    # Áp dụng giới hạn tài nguyên tiết kiệm cho MinIO
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
